version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Container
          command: docker build -t app .
      - run:
          name: Run Docker Tests
          command: |
            # Get environment variable CodeCov might want
            ci_env=`bash <(curl -s https://codecov.io/env)`
            # Create container
            docker create \
            $ci_env \
            --name app \
            app make codecov
            # Run the tests
            docker start -a app
            # Retrieve the results
            docker cp app:/app/test-results.xml .
            # Clean up
            docker rm app
      - store_test_results:
          path: .

workflows:
  default:
    jobs:
      - build
