version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Git debug
          command: |
            set -x
            docker create --rm \
            --name app \
            cimg/base:stable \
            sh -c 'set -x; cd /app; ls -la .git; cat .git/HEAD'
            mkdir dummy  # really, THIS is the way?
            docker cp dummy app:/app
            docker cp .git app:/app/.git
            docker start -a app
      - run:
          name: Build Docker Container
          command: docker build -t app .
      - run:
          name: Run Docker Tests
          command: |
            docker create --rm \
            -e TRAVIS_JOB_ID=#$CIRCLE_BUILD_NUM \
            --name app \
            app make coveralls
            docker cp .git app:/app/.git
            docker start -a app

workflows:
  default:
    jobs:
      - build
