version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Container
          command: docker build -t app .
      - run:
          name: Run Docker Tests
          command: |
            docker create --rm \
            -e TRAVIS_JOB_ID=#$CIRCLE_BUILD_NUM \
            --name app \
            app make coveralls
	    # CircleCI doesn't allow mounts/volumes on the docker runner
            docker cp .git app:/app/.git
            docker start -a app

workflows:
  default:
    jobs:
      - build
