version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Git debug
          command: |
            ls -la .git
            cat .git/HEAD
            docker run --rm -v $(pwd)/.git:/app/.git \
            cimg/base:stable \
            sh -c "set +x; cd /app; ls -la .git; cat .git/HEAD"
      - run:
          name: Build Docker Container
          command: docker build -t app .
      - run:
          name: Run Docker Tests
          command: |
            docker run --rm -v $(pwd)/.git:/app/.git:ro,Z \
            -e TRAVIS_JOB_ID=#$CIRCLE_BUILD_NUM \
            app make coveralls

workflows:
  default:
    jobs:
      - build
