version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Container
          command: docker build -t $CIRCLE_PROJECT_REPONAME .
      - run:
          name: Debug
          command: |
            set -x
            docker run --rm \
            -e TRAVIS_JOB_ID=$CIRCLE_BUILD_NUM \
            $CIRCLE_PROJECT_REPONAME env | sort
      - run:
          name: Run Docker Tests
          command: |
            docker run --rm -v $(pwd)/.git:/src/.git:ro,Z
            -e TRAVIS_JOB_ID=#$CIRCLE_BUILD_NUM \
            $CIRCLE_PROJECT_REPONAME make coveralls

workflows:
  default:
    jobs:
      - build
