version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Container
          command: docker build -t app .
      - run:
          name: Run Docker Tests
          command: |
            # Create container
            docker create \
            -e TRAVIS_JOB_ID=$CIRCLE_BUILD_NUM \
            -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN \
            --name app \
            app make codecov
            # # CircleCI doesn't allow mounts/volumes on the docker runner
            # docker cp .git app:/app/.git  # disabled for testing purposes
            # Run the tests
            docker start -a app
            # Retrieve the results
            docker cp app:/app/test-results.xml .
            # Clean up
            docker rm app
      - store_test_results:
          path: .

workflows:
  default:
    jobs:
      - build
